Refactor the JSON-RPC connection
grisp/grisp_connect pull request #52
Opened 2024-11-26 15:46 UTC by sylane

### Changed

- The name of the grisp_connect configuration key to control the timout of
individual JSON-RPC requests changed from ws_requests_timeout ot
ws_request_timeout.
- Le default log filter changed to trying to filter out only some messages to
filtering out all progress messages, as it wasn't working reliably.
- The connection is not a persistent process anymore, it is now a transiant
process handling a connection and dying when the connection is closed.
- Internally, the JSON-RPC is parsed into a list of atom or binaries to pave the
road for namespaces. foo.bar.Buz is parsed into [foo, bar, <<"Buz">>] (if foo
and bar are already existing atoms, but 'Buz' is not).

## Fixed

- The client is now waiting 1 second before trying to reconnect when it gets
disconnected fomr the server.

2024-11-26 16:31 UTC, maehjam commented
Can you explain to me the different purposes of the modules `grisp_connect_connection`, `grisp_connect_client` and `grisp_connect_jsonrpc`. First impression is that it's all mixed up. This needs better documentation.

2024-11-26 16:37 UTC, sylane commented
@maehjam It is less mixed up than it was, but I get that it may still be under documented. grisp_connect_jsonrpc is only doing JSON-RPC encoding/decoding, grisp_connect_connection encapsulate a JSON-RPC connection, and grisp_connect_client encapsulate the girps_connect client protocol.

2024-12-03 15:56 UTC, maehjam reviewed
1. The logger changes and architecture changes of the websocket connection shouldn't be in the same PR. Both are changes in parts that are hard to test. They each need very careful testing and probably manual testing in addition to the automatic testing.
2. Is this working with the current `grisp_manager` implementation or do we need to adjust `grisp_manager` as well?

2024-12-03 15:56 UTC, maehjam commented on src/grisp_connect_connection.erl
I feel with the timeouts and the distinction between connected and disconnected in `handle_call` this would be much better readable as a `gen_statem`. The module name is a bit strange, I liked `grisp_connect_ws` better.

2025-01-08 16:23 UTC, peerst commented
This PR is stuck for a while now.  Adding 1860 Lines and removing 430 is clearly beyond the size of reviewability (max 500 lines).  How do we want to proceed with this?  @sylane can you split it up in several PRs?

Also from what I can see so far: it looks in parts more like a rewrite than a refactoring.  I'm not sure if that is due to too many refactoring steps stacked on top of each other so it only looks like a rewrite?  

Rewriting or large refactors have a tendency to sneak in new bugs, so therefore require substantial improvement of testing at the same time: is that the case here?

How is the relationship between this code and DAB?  Will this eventually end up in DAB?  Parts of it?  I don't want to have to maintain two forks of the same thing if that is the actual case.

2025-01-08 17:00 UTC, sylane commented
@peerst This is already only some part of a bigger changeset that I split so it was simpler to review... Some changes already got merged in, but there is still more changes pending. The changes here are to go toward having a self-contained independent json-rpc client instead of having json-rpc logic spread everywhere in grisp-connect. So the connection is indeed a rewrite, but all the rest are changes to mostly remove things that are now abstracted by the new connection. I don't think I could easily split the changes further. For the testing, I wrote more tests, and I made the code more test-friendly, as the json-rpc connection can be tested completely independently. If we want more tests for it, I could write more, this shouldn't be complicated.

2025-01-17 16:49 UTC, ziopio requested changes

2025-01-17 16:49 UTC, ziopio commented on src/grisp_connect_connection.erl
> +-if(?ENABLE_TRACE =:= true).
So is it possible to step over written definitions?

2025-01-17 16:49 UTC, ziopio commented on src/grisp_connect_client.erl
> +    case jarl:post(Conn, Method, Params2, ReqCtx) of
Why do you have` jarl:request` and` jarl:post` and you only use `jarl:post` Json RPC does not have the concept of a `post` but only request/notify

2025-01-17 16:49 UTC, ziopio commented on src/grisp_connect_client.erl
> +    case jarl:post(Conn, Method, Params2, ReqCtx) of
Also, in the jarl application you have this 700+ lines `gen_statem` that implements JsonRPC message handling and GUN.
Could these 2 concepts be split in 2 modules in Jarl,as it was in `grisp_connect` before this PR?
The jarl_connection module looks already too big

2025-01-21 14:47 UTC, sylane commented on src/grisp_connect.app.src
> +                    {disable_progress, {fun logger_filters:progress/2, stop}}
I am not 100% sure that it make things better. It looked better for me, and this is the common solution I found about our problem with logging certificate, but others should test it too.

2025-01-21 15:25 UTC, sylane commented on src/grisp_connect_connection.erl
> +-if(?ENABLE_TRACE =:= true).
@ziopio Not sure what you mean by that...

2025-01-21 15:28 UTC, sylane commented on src/grisp_connect_client.erl
> +    case jarl:post(Conn, Method, Params2, ReqCtx) of
As the idea was first to consolidate the JSON-RPC in a single place in grisp_connect first, this is what I did with jarl_connection, but then I moved it out of grisp_connect to make the PR more compact. Maybe this could be refactored again to split again, not sure if it is needed now though, I am open to it. The main reason I think it was more important before is because the guns management and the json-rpc was done in different processes before, now it is done in the same process.

2025-01-21 15:29 UTC, sylane commented on src/grisp_connect_client.erl
> +    case jarl:post(Conn, Method, Params2, ReqCtx) of
@maehjam What do you think about that @maehjam ?

2025-01-22 10:48 UTC, ziopio commented on src/grisp_connect_connection.erl
> +-if(?ENABLE_TRACE =:= true).
You define `ENABLE_TRACE = false` and then use it right away to check if it is true. Without context this looks like the if section will never apply.

2025-01-22 10:50 UTC, ziopio commented on src/grisp_connect_client.erl
> +    case jarl:post(Conn, Method, Params2, ReqCtx) of
@sylane still... why `post` instead of `request` ?

2025-01-22 15:31 UTC, maehjam commented on src/grisp_connect_client.erl
> +    case jarl:post(Conn, Method, Params2, ReqCtx) of
I'm also confused what `post` is. There is no documentation in `jarl` about it.

2025-01-22 15:34 UTC, sylane commented on src/grisp_connect_client.erl
> +    case jarl:post(Conn, Method, Params2, ReqCtx) of
post it to asynchronously post a request, request is doing a post and wait for the response so it is synchronous

2025-01-22 15:35 UTC, sylane commented on src/grisp_connect_client.erl
> +    case jarl:post(Conn, Method, Params2, ReqCtx) of
When using post, you need to handle the asynchronous messages with either a response or an error.

2025-01-22 17:01 UTC, maehjam commented
Sorry, I still don't think I'm able to review this. It is too much changes at once. Now, we have changes here and a new app `jarl` to review together. Splitting it up, didn't reduce the difficulty to review.

I feel before we can review the changes here, we need to review `jarl` which is 2000+ lines in one commit without any documentation. I looked into it and it's really hard to read. For example a function named `jarl:error/5` can do different things: Did we receive a json-rpc error from the server or do we want to send one or something else? And what is the difference between `jarl:error/5` and `jarl:reply/2`, when `error` is about replying an error? The naming of `jarl:post/4` was already discussed inline. The name `post` is usually associated with HTTP and has no equivalent in JSON-RPC.

Furthermore, I have to note: Even when we move a big chunk of this rewrite in a separate library that is still a big rewrite. We already have two JSON-RPC client implementations here in `grisp_connect` as well as in `dab` and should reuse the knowledge and preferably also the implementations. I like the idea of a reusable JSON-RPC client app, but that should be developed together with the people who worked on the implementations in `grisp_connect` and `dab` to use their experience. Just putting us here as reviewers after implementing 2000+ lines doesn't work. That is too much to read while trying to compare with the existing work (without readable diffs).

If we want this big rewrite. I would prefer that we first develop `jarl` starting with the concept and general architecture that we discuss and agree on as a team. Then we can review the implementation in smaller steps (commits). 

We should make sure a library like `jarl` is usable by `grisp_connect` as well as by `dab`, because otherwise what is the point of a separate app? Can you tell me whether `jarl` can be used in `dab` as well?

2025-01-23 12:06 UTC, sylane commented
This PR is only around 330+330- lines if you don't count tests, docs and config, it is big but I don't think it is unrasonable. I understand that moves some review work to jarl, but it is now a self-contains library with limited scope and API. They weren't any documentation with the old jrpc-code, at least now theres is well defined type specifications. I could add more documentation, this is not a problem, but would that change your mind ?
API jarl:error/5 is not doing different things, it is sending an error to the connection, either in the context of a request or not, I am not sure what you mean by it is doing different things. Everything you receive from the json-rpc peer, you get either synchronously when using jarl:request, or asynchronously with messages definied in jarl type specs. Post is used in http but convei some meaning too, it as a strong meaning of asynchronicity this is why it is used there, but this is just naming, if this was the only problem it would be easy to resolve, right ?
I am curious about what would be the smaller steps to implement a json-rpc client library, and I don't see why this couldn't be used by DAB, we could discuss that if you were interested.
Anyway, I am not sure how to react to your comment, the feeling is that there is nothing to do in your opinion to get this to a mergable state, you have issue with some naming and with documentation, all good points, but I don't feel that would change your opinion on the PR... Should I just delete the PR and the branch and forget about it ?

2025-01-23 12:20 UTC, ziopio commented
@sylane  I think we should discuss jarl usage, architecture and API. This PR would be ok but it relie on us accepting jarl as is.
The best would be:
- you present jarl to the team
- we try to understand if and how the design would also help DAB or be improved using DAB design
- We agree on an API that can be generic and reusable ecc
- We define what needs to change from what jarl is now.
- You rewrite Jarl with incremental PRs so we can quickly follow the development.
So the PR can be parked here until we are fine with jarl.

2025-01-23 17:55 UTC, maehjam commented
Just to clear it up: The examples I mentioned about the function naming `error` and `post` in `jarl` were just to point out one of the things that make it difficult to read the code. The names were not self-explanatory to me, and like that I find most of the code hard to understand. The bigger issue is that it's just too much at once. Since it's one big commit, I can't even follow your steps of implementation to get the idea und structure that is probably totally clear to you as the author.

Thanks @ziopio for the proposal on how we can continue here. That is for sure one way. I would like a decision from @peerst and the rest of the team on how we proceed, before we put too much time into it. That can be discussed after the first point of presenting `jarl` to the team.

2025-02-07 09:53 UTC, maehjam requested changes
I reviewed the first 8 files and found that the JSON-RPC API must be broken, since errors are not handled. I was wondering whether the tests wouldn't catch that. Please extend `grisp_connect_api_SUITE` to better cover the API. It only tests two methods.

I stop my review here till the tests pass.

There are already some change requests in the inline comments. 

One other thing I noticed is that `rebar.lock` is missing. With the new `jarl` library as a dependency it should be updated.

2025-02-07 09:53 UTC, maehjam commented on docs/grisp_connect_architecture.md
> + - Send generic errors
That formulation is a bit unclear. Do you mean the automatic sending for predefined JSON-RPC errors from the JSON-RPC specifications? Then instead of "generic errors" rephrase it to "predefined JSON-PRC errors".

2025-02-07 09:53 UTC, maehjam commented on docs/grisp_connect_architecture.md
> +term, that will given back when receiving a response or an error for this
"that will <ins>be</ins> given back"

2025-02-07 09:53 UTC, maehjam commented on config/dev.config
> +                    {disable_progress, {fun logger_filters:progress/2, stop}}
It would be good to keep the comment why we do that here and also add it to `local.config`, `test.config`.

2025-02-07 09:53 UTC, maehjam commented on src/grisp_connect_api.erl
> +% @doc Handles requests, notifications and errors from grisp.io.
I see it only handling notifications and requests, not errors.

2025-02-07 09:53 UTC, maehjam commented on src/grisp_connect_api.erl
> +                {error, already_updating, undefined, undefined, ID};
This error is not defined in `grisp_connect_client`.

2025-02-07 09:53 UTC, maehjam commented on src/grisp_connect_api.erl
> +                {error, grisp_updater_unavailable, undefined, undefined, ID};
All the error tuples are not handled as return values is `grisp_connect_client:handle_connection_message/2`.

2025-02-07 11:54 UTC, sylane commented on CHANGELOG.md
> +disconnected from the server.
It is done in in grisp_connect_client, in the connecting function.

2025-02-07 12:17 UTC, maehjam commented on CHANGELOG.md
> +disconnected from the server.
I did look again and found it in `waiting_ip`. So that is a counter intuitive place to do it. I was expecting it in `connecting` somewhere, for example in `enter` there. Is there some deeper reason to put it in `waiting_ip` that I don't see?

2025-02-07 15:03 UTC, sylane commented on src/grisp_connect_api.erl
> +% @doc Handles requests, notifications and errors from grisp.io.
It wasn't before the refactor IIRC, so I didn't add it.

2025-02-07 15:07 UTC, sylane commented on CHANGELOG.md
> +disconnected from the server.
It doesn't make much sense to not check again if the IP is available after a connection error, so going back to waiting_ip seems better, and as we want to wait between each ip checks, better leveraging this than behaving differently if we were connected or not before then.

2025-02-07 15:19 UTC, sylane commented on src/grisp_connect_api.erl
> +% @doc Handles requests, notifications and errors from grisp.io.
In fact, the request errors are handled in grisp_cllient: https://github.com/grisp/grisp_connect/blob/sylane/cleanup-connection/src/grisp_connect_client.erl#L260

2025-02-07 16:33 UTC, maehjam commented on src/grisp_connect_api.erl
> +% @doc Handles requests, notifications and errors from grisp.io.
It was done before the refactoring (you can clearly see it in the diff) and it had a totally different documentation.
So that documentation is about your change and it doesn't fit. Fix it.

2025-02-07 16:38 UTC, maehjam commented on CHANGELOG.md
> +disconnected from the server.
But it's not leveraged. The waiting between `waiting_ip` is implemented in line 156 and the waiting between connects in line 144. They are not related at all.

2025-02-07 16:41 UTC, sylane commented on src/grisp_connect_api.erl
> +% @doc Handles requests, notifications and errors from grisp.io.
You are right, and I remembered that and posted the second comment about where the error is handled. Now the error are handled in a generic way in grisp_connect_client, line 260

2025-02-07 16:50 UTC, sylane commented on CHANGELOG.md
> +disconnected from the server.
It is, because by switching to state `waiting_ip` from either the `connecting` or `connected` state you will have the correct delay. Maybe using `repeat_state` instead of `next_state` at line 156 and not registering a new `state_timeout` would make it clearer for you ? This way the timeout would only be setup in `waiting_ip` enter function.

2025-02-11 10:36 UTC, maehjam commented on test/grisp_connect_log_SUITE.erl
> +reset_log(LasSeq) ->
LasSeq -> LastSeq

2025-02-12 11:05 UTC, maehjam approved these changes
🚀

2025-02-13 09:28 UTC, ziopio approved these changes

2025-02-13 10:02 UTC, merged